# Generated by the release workflow. Do not edit by hand.
class Secretenv < Formula
  desc "Run any process with secrets from all your backends"
  homepage "https://secretenv.dev"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.1.1/secretenv-v0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "f628fd3485055b1b21eb3eb76910fe403567c14c2f604b95b291b6e29b931307"
    else
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.1.1/secretenv-v0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "bcb58caff9662aafba18ea0ab3e9f3b7e240989cc69b1bac34f12367245542dc"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.1.1/secretenv-v0.1.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "576958942a793b584d63f0836624a84e4ccd6e01fbc6f2eea97f984e526e9dfa"
    else
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.1.1/secretenv-v0.1.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ce438d6890281f3ae3b20de7d8c236f4d90d84830239c47f748bb5ce340c3e39"
    end
  end

  def install
    bin.install "secretenv"
  end

  test do
    assert_match "secretenv 0.1.1", shell_output("#{bin}/secretenv --version")
  end
end
