# Generated by the release workflow. Do not edit by hand.
class Secretenv < Formula
  desc "Run any process with secrets from all your backends"
  homepage "https://secretenv.io"
  version "0.18.0"
  license "AGPL-3.0-only"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.18.0/secretenv-v0.18.0-aarch64-apple-darwin.tar.gz"
      sha256 "abef130f72baa52fefacfc5c808e9258ec471f5815245b51bdbbe720688965b4"
    else
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.18.0/secretenv-v0.18.0-x86_64-apple-darwin.tar.gz"
      sha256 "1d7a304d321c1258aec09344bbab2b8803a6bafe55df439c4a9926ec24025469"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.18.0/secretenv-v0.18.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1cfdbfc376b6bc43321cf9e8f4723e4ced9bf0e6886807784eff392814f558d7"
    else
      url "https://github.com/TechAlchemistX/secretenv/releases/download/v0.18.0/secretenv-v0.18.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "1dbcd0ce0e0849957fb3f65e55f475d9a580132091f3b714d880993d2c976467"
    end
  end

  def install
    bin.install "secretenv"
    generate_completions_from_executable(bin/"secretenv", "completions")
  end

  test do
    assert_match "secretenv 0.18.0", shell_output("#{bin}/secretenv --version")
  end
end
